[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 15

[font.bold]
family = "Iosevka Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Nerd Font"
style = "Light"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0
